### ISSUE TITLE
Can´t find the function EVGH_TripExternalizations2CosmosDB 

### ISSUE THREAD

**Issue by dmelgarejoPDESGO** [Azure-Samples/Serverless-microservices-reference-architecture#2]
In the documentation we must attach an eventgrid topic to this function, but it doesn´t exist.

In other things, how do I test this solution?

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by joelhulen** [comment]
That function is located within the Node.js Function App (trip archiver).

You can test the solution by running the Function Apps locally on your machine. You can also test the web app locally by navigating to the web app root, then running `npm run serve`. Please let me know if you need more details.

**Comment by joelhulen** [comment]
Closing due to lack of response. Please re-open if you are still experiencing this issue.
